USE `salesledger`;
INSERT INTO `MERCHANDISE` ( DESCRIPTION, PRICE, SELLER, AVAILABLE) VALUES( "Ravensburger San Juan Bopard Game", 70.99,   27,  1);
INSERT INTO `MERCHANDISE` ( DESCRIPTION, PRICE, SELLER, AVAILABLE) VALUES( "Manhattan Toy Zoo Winkel Owl Rattle and Sensory Teether", 30.99,   38,  1);
INSERT INTO `MERCHANDISE` ( DESCRIPTION, PRICE, SELLER, AVAILABLE) VALUES( "Thomas & Friends Fisher-Price Wooden Railway, James Engine", 150.99,   58,  2);
