USE `salesledger`;
INSERT INTO `MERCHANDISE` ( DESCRIPTION, PRICE, SELLER, AVAILABLE) VALUES( "The Flyers Bay Rc Stunt 360 Remote Control Car, Multicolor", 67.90,  125,  1);
INSERT INTO `MERCHANDISE` ( DESCRIPTION, PRICE, SELLER, AVAILABLE) VALUES( "Creative's Fun with Words pack of 1", 29.40,  200,  2);
INSERT INTO `MERCHANDISE` ( DESCRIPTION, PRICE, SELLER, AVAILABLE) VALUES( "Intex Inflatable Rectangular Pool, Multi Color", 10.99,  142,  2);
